export const FETCHING_ARTICLES = 'FETCHING_ARTICLES';
export const SET_ARTICLES = 'SET_ARTICLES';
export const FETCHING_ARTICLES_FAILED = 'FETCHING_ARTICLES_FAILED';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SET_ACTIVE_SOURCE = 'SET_ACTIVE_SOURCE';
